console.log("Hello")
console.log("Tapat Toungsakul")
console.log("My website")
let x=prompt('Enter')
console.log("ธภัทร ตึ้งสกุล")
console.log("ออโต้")
console.log("0982625255")
console.log("Au To")
console.log("txpxt_xuto")
console.log("txpxt-xuto")